### ISSUE TITLE
Consider disabling Coveralls "Leave Comments" option

### ISSUE THREAD

**Issue by anonimal** [monero-project/bitmonero#1023]
Since I don't know if this feature is actually useful to anyone else, here's an open issue to get input on the matter.

Presently, Coveralls will spam (and is spamming) GitHub notifications with commit comments on watched repos; this includes bitmonero. This makes it difficult to read actually useful human comments in PR's and commits.

Un-checking "Leave Comments?" in https://coveralls.io/github/monero-project/bitmonero/settings should solve the problem and won't effect coverage.

**Comment by expez** [comment]
I'm watching this repo and I find the current behavior annoying.

**Comment by fluffypony** [comment]
I agree - I'm going to stop it now

**Comment by fluffypony** [comment]
Fixed
