### ISSUE TITLE
enhancement request: option to disable upnp

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#107]

**Comment by iamsmooth** [comment]
seems to not be in master, so still needs to be merged

**Comment by fluffypony** [comment]
@smooth this PR: https://github.com/monero-project/bitmonero/pull/217 is the hold up, that doesn't build on OS X or FreeBSD.

**Comment by rfree** [comment]
It is merged now into master, option is --no-igd

**Comment by Geremia** [comment]
@fluffypony How do I disable `miniupnp` and `libunbound` at compile-time?
