### ISSUE TITLE
Segfaut when request rpc cut before bitmonerod send response ?

### ISSUE THREAD

**Issue by perl5577** [monero-project/bitmonero#115]
One server
Aug 31 19:43:25 sd-52200 kernel: [3744359.110587] traps: bitmonerod[38545] general protection ip:558000 sp:7fffc205a0e0 error:0 in bitmonerod[400000+27a000]
Aug 31 22:56:44 sd-52200 kernel: [3755969.543315] bitmonerod[9622]: segfault at d4 ip 0000000000558000 sp 00007fff69c9ba60 error 4 in bitmonerod[400000+27a000]
Sep  2 12:52:20 sd-52200 kernel: [3892643.870889] bitmonerod[41405]: segfault at 2d ip 0000000000558000 sp 00007fffa5069de0 error 4 in bitmonerod[400000+27a000]
Sep  2 21:12:01 sd-52200 kernel: [3922655.656492] traps: bitmonerod[49690] general protection ip:558000 sp:7fff909b5020 error:0 in bitmonerod[400000+27a000]
Sep  2 23:48:08 sd-52200 kernel: [3932031.486473] traps: bitmonerod[59552] general protection ip:558000 sp:7ffff0dab060 error:0 in bitmonerod[400000+27a000]
Sep  2 23:51:19 sd-52200 kernel: [3932223.256345] bitmonerod[61345]: segfault at 29 ip 0000000000558000 sp 00007fff11cb4aa0 error 4 in bitmonerod[400000+27a000]

Other server
Aug 31 22:56:02 sd-61632 kernel: [3093513.417808] bitmonerod[61424]: segfault at 49edc80002e ip 0000000000538500 sp 00007fff3c8dba20 error 4 in bitmonerod[400000+27a000]
Sep  2 13:02:44 sd-61632 kernel: [3230652.364691] bitmonerod[29388]: segfault at 31 ip 0000000000538517 sp 00007fff153345e0 error 6 in bitmonerod[400000+27a000]

As not impact on my pool , I use multibitmonerod .
Seems to occur if an RPC request getblocktemplate cuts before bitmonerod send response.
After segfault bitmonerod is never OK

**Comment by fluffypony** [comment]
Is this still happening?

**Comment by moneromooo-monero** [comment]
What does "an RPC request getblocktemplate cuts before bitmonerod send response" mean ? The client closes connection after sending the request, but before a reply is received ?

**Comment by perl5577** [comment]
You can close
