### ISSUE TITLE
inconsistency in reported block height

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#130]
2014-Sep-11 22:00:47.482087 [P2P8][121.40.157.40:18080 OUT]Sync data returned unknown top block: 214132 -> 214133 [1 blocks (0 days) behind] 
SYNCHRONIZATION started
2014-Sep-11 22:00:47.482393 [P2P8]Remote top block height: **214133**, id: <**7b37dc73f030b0cf9dae82162fcb41ce306d585994aba8aced6a0961b8316de8**>
2014-Sep-11 22:00:47.850375 [P2P3]+++++ BLOCK SUCCESSFULLY ADDED
id:     <**7b37dc73f030b0cf9dae82162fcb41ce306d585994aba8aced6a0961b8316de8**>
PoW:    <47b03c4f44588505660263214bc7cb308c171ca8faa04090e515fb8d02000000>
HEIGHT **214132**, difficulty:      1209222503

**Comment by fluffypony** [comment]
This is still happening, assigning to @moneromooo-monero

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/737
