### ISSUE TITLE
simplewallet starts refresh at wrong block

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#135]
Upon refresh there is a message in simplewallet.log that the first block received is already known. Likely off-by-one error.

2014-Sep-12 23:02:45.767691 Starting refresh...
**2014-Sep-12 23:02:45.810703 Block is already in blockchain: 4c0917d3f62781d39ab67e0f21c1397a4f706424c206ec3bea96b44a4bf5ea81**
2014-Sep-12 23:02:45.812681 Processed block: <f7eca35848ba7203b6cd08481bdec4eead26daf24b49cef50c4b57c5114479d3>, height 215209, 2(2/0)ms
2014-Sep-12 23:02:45.913911 Processed block: <99eb11332ccf81d6e4bb01b135b62327e0d9c9e150af6a08e6ecb073abc22aed>, height 215210, 71(1/70)ms

**Comment by fluffypony** [comment]
Appears to be resolved
