### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by ehmry** [monero-project/bitmonero#147]
IPV6 support is missing in p2p and rpc.

I've seen it mentioned that networking could get a rewrite (https://github.com/monero-project/bitmonero/issues/60), are there any vague ideas of what that rewrite would look like?

**Comment by gurghet** [comment]
+1

**Comment by x1ddos** [comment]
Just wondering, why was this closed?

**Comment by fluffypony** [comment]
@x1ddos the person who created the issue closed it, no clue why

**Comment by fluffypony** [comment]
@x1ddos FYI this is solved in PR #4851
