### ISSUE TITLE
Failed to generate new wallet 

### ISSUE THREAD

**Issue by netmonk** [monero-project/bitmonero#193]
netmonk@plonky:~/bm/bm2/bitmonero/build/release/bin$ ./simplewallet --daemon-address xmr1.coolmining.club:5012 
bitmonero wallet v0.8.8.4-e1555fd
Specify wallet file name (e.g., wallet.bin). If the wallet doesn't exist, it will be created.
Wallet file name: ~/donation.bin
The wallet doesn't exist, generating new one
password: ********
List of available languages for your wallet's seed:
0 : English
1 : Spanish
2 : Portuguese
3 : Japanese
Enter the number corresponding to the language of your choice: 0
Error: failed to generate new wallet: failed to save file "~/donation.bin.keys"

When asked for wallet name, it seems "~/"  in the name of wallet to instruct wich path to save the file makes the whole process fail on linux.

**Comment by benma** [comment]
I have the same issue. No matter what name or path I enter, it fails. Some files are generated, though:

mywallet.address.txt  mywallet.keys  mywallet.new

**Comment by fhirschmann** [comment]
Can you try it again with `--wallet-file=/home/$USER/.bitmonero/wallet.dat` instead of `~/.bitmonero/wallet.dat`?

Simplewallet does not seem to expand `~` to `/home/$USER`.

**Comment by moneromooo-monero** [comment]
As said above, ~ is a shell thing, so ~/something would save in a relative directory called ~, which you probably don't have. This can probably be closed. For the general case, I don't think we want to create directories if they don't exist, but I could be persuaded otherwise.
