### ISSUE TITLE
tries to write log files to the location of the executable

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#194]
simplewallet (and maybe bitmonerod?) uses the location of the executable to store the log files. This might be normal for Windows, but is clearly broken for linux (where executable would normally go in some non-writeable bin) and probably mac too.

In the case of simplewallet it is reasonable for the log file to go the same place as the wallet file. bitmonerod might write its log file into .bitmonero although a package manager build should probably go to a standard log location, so there should be a build option for this.

**Comment by fluffypony** [comment]
I believe this is fixed now with the latest batch of merges.
