### ISSUE TITLE
Transaction would be too large

### ISSUE THREAD

**Issue by fish34** [monero-project/bitmonero#199]
Today in the log error when wallet daemon try to make payouts:
Error with transfer RPC request to wallet daemon {"code":-4,"message":"Transaction would be too large.  try /transfer_split."}
What can we do with this error at the pool?

**Comment by fluffypony** [comment]
Closed

**Comment by reeyon** [comment]
@fluffypony 
Hi i know this is old. But hope you can help to answer my question.
you'd mentioned to use transfer_split in API call.. 
where can I change it on the pool software?

**Comment by SamsungGalaxyPlayer** [comment]
@reeyon this is a better question for [StackExchange](https://monero.stackexchange.com).
