### ISSUE TITLE
How to use the wallet.bin generated by windows simplewallet in linux

### ISSUE THREAD

**Issue by zhaoxiting1997** [monero-project/bitmonero#207]
I have a wallet backup of the windows simplewallet ,including wallet.bin,wallet.bin.key.And it can be restore in the windows.However,when I use the linux simplewallet downloaded from the offical website it goes wrong.It said that ''Error: failed to load wallet: failed to read file "wallet.bin". here is the log 2014-Dec-24 11:00:32.075064 bitmonero wallet v0.8.8.4-release 2014-Dec-24 11:00:38.797845 Loaded wallet keys file, with public address: 42c2k5oa9J5ecqRSAEKTKED35V7TU6bdRPFYuSDFN2cR2VCZgpiLBCn95Wnvs83sfpcq8Bif61MvL5AbqTt5RJ9xJrPi2V3 2014-Dec-24 11:00:38.798040 ERROR /home/ric/bitmonero/src/common/boost_serialization_helper.h:108 Exception at [unserialize_obj_from_file], what=incompatible native format - size of long 2014-Dec-24 11:00:38.798063 ERROR /home/ric/bitmonero/src/wallet/wallet2.cpp:576 !r. THROW EXCEPTION: error::file_read_error 2014-Dec-24 11:00:38.798082 /home/ric/bitmonero/src/wallet/wallet2.cpp:576:N5tools5error15file_error_baseILi2EEE: failed to read file "wallet.bin" 2014-Dec-24 11:00:38.798121 Error: failed to load wallet: failed to read file "wallet.bin" 2014-Dec-24 11:00:38.798165 ERROR /home/ric/bitmonero/src/simplewallet/simplewallet.cpp:394 could not open account 2014-Dec-24 11:00:38.798183 ERROR /home/ric/bitmonero/src/simplewallet/simplewallet.cpp:1211 Failed to initialize wallet

**Comment by fluffypony** [comment]
Sorry I only got to this now, January was a blur. You unfortunately can't move wallets between Windows <-> Linux/OS X, you have to restore from your seed.
