### ISSUE TITLE
Command RPC /gettransactions not work

### ISSUE THREAD

**Issue by perl5577** [monero-project/bitmonero#213]
Impossible get information and blob for on TX include on blockchain or poolstate

curl --connect-timeout 1 10.90.162.142:19004/gettransactions  -d '{"txs_hashes" : "024b64904ee62f622a756ef3ca76da5ad86bb3abcc00d72f7"}' 
{
  "status": "OK"
}
curl --connect-timeout 1 10.90.162.142:19004/gettransactions  -d '{"txs_hashes" : "bullshit"}' 
{
  "status": "OK"
}
curl --connect-timeout 1 10.90.162.142:19004/gettransactions  -d '{"params":{"txs_hashes" : "024b64904ee62f622a756ef3ca76da5ad86bb3abcc00d72f7"}}' 
{
  "status": "OK"
}
curl --connect-timeout 1 10.90.162.142:19004/gettransactions  -d '{"params":{"bullshit" : "024b64904ee62f622a756ef3ca76da5ad86bb3abcc00d72f7"}}' 
{
  "status": "OK"
}

**Comment by perl5577** [comment]
Thanks warptangent,
Need used List for txs_hashes

 curl --connect-timeout 1 10.90.162.142:19004/gettransactions  -d '{"txs_hashes" : ["024b64904ee62f622a756ef3ca76da5ad86bb3abcc00d72f773dd20b9a2df207"]}' 
{
  "status": "OK",
  "txs_as_hex": ["010009028090cad2c60e02d0f310c0c31219e58e382ff37b49df20a92b6d61e164a3a3d2b1c3454e0b49395eea331f10650280b081daaf1402b0b501a6b10dbeb3614bf1112b1926469886a7b1b1de621816e323e508ab9c5ff302f4c6fb7d028090cad2c60e02b9fb04d8bb1ebfee0f33c676aed7e6637dc59aaea1308e54532241eae3dd4b39f452296378690280b081daaf1402f58704c6dd0ae06ee90813df6d5a528ccd2bf42b568ae0a2ec870043ed9c74a78dec1df21c940280c0ee8ed20b02d2ab0bb7d8082c1b41ef97867acb23efe86074b26f5d8fa7e3f55395f66ec352ed94105245aa0280a0b787e90502b7911ff1b50df929f05f0dfaf76192b508d152e96b6262d5a2d81d31605e26be1c50c81da72d0280d0dbc3f402029dbb1ae6bb0f442c536fcfba7f694971f14ade415c1a971b76ccedc3098aed2de986a780213e0280c0fc82aa0202af8505d6d001b705092ce02ca44bd4cfb223d0cbfebd93f0a97028da6a74b492af1c9c35c0fd0280c0a8ca9a3a02839301c3ed0be3bfdab1f0b3da3d0dfd6e58500feac9124dc47beb8380ff66bad7c724c108ec0a80f8cce2840202562e503db2628d2eb82cab4ae6e61f7a8aafc2d24151ac0b494d84867d01a56c80d0dbc3f402027dd4aedc198b680d3c6512a4c10bff52799024646cd44fc09766a21aaba4100c80d0dbc3f40202b92e294e2a0e9a5b53305f589e4bd6a5b4334ae9c97d812d8d6a75cd3817004480a0b787e905026d453d25fc91534daabdce42f02bf7d3b3e21f41ea89230712be99564cf739ad80a0b787e90502816c234693924a6b3ab7753374c71b17f4ccf49c2b8ec8ea60c631927402f2af80a0b787e90502b1a0bc252cf2d6ba68dd5b5c497b2a3090457da73cae7bb1becee0418c0d3e698090cad2c60e0250563f2421b997e59c99897ae95c5902391eee17dbf3295e9bfb7dfb5586a3b78080dd9da417024d734505e8c67a5e202bf3e3c32171031de54c7d8f142cfc21dcb28b3b87404080a094a58d1d020ba132f7f650bc4dc040fdc616b408ab211739cd6322856752d30d29b87d6e5a80c0a8ca9a3a02c64db3e53254bfe59d5d2d496b638447c06eac857a93c524f3de3f5713139a46210197cc2a41a5cc8f7a31ad03cceef47deca0ec909891b243aa375168f844c4624596d8b2b9150d0d6483256c0164907d0647483c7e62b8e5b0b766ac3e7ce0840804f2bb3aee2b7d9906c3c10cd5d2a3ac38425126731349d97485da30192bd607694207a7f599b8b57cad1b1ed068edb3e800866568389cd02d8f1a3f17a7eb017e8d76eba64235b4f6d19c10735192074c6b2d7f0e8cc4dd6b0827234f81b8003deb40e76a54524b8ef3f3a0a3a96da2de31aea0752c71b3f190fad76888ce058630dc01a5965a3a9b880ecfb7ce978fd1091961d251a1ac84d49867d4c03f0f6a21eebac132b0efcb144056ef030eab711deed91ee8e9cb8b7dbad0eaa8b2079889caa024d9420025451fde20882f7d545dc9b03ce97f5f1809f73a3defc90a17d85a9577295622412fba79dfca9442b7f748ebfd8d2424bce704e796c11904b493f3a8bdd56bd41026e526e09ecda90dd878b6caa4812f2a91243f2038e6023424bb02ab607853d2d801e901e540d1d6ef18d3c41a3566303a37bf04ce4205cb65d79987ee64eb0ff2c3abedbc6384d455f092b07f4eacff790764ad37c402a5481104043764fb3ce5d3da0c526106fa79483fcf6e8b5f56998083a6a39d0a1ad2fbcd80eee31eaa5843942859339a8073deca615a520dc010e27a3b86300141cca75e53d1fe1aeab15d6c7a5c4e2ec01e32fe5aafdd6cbaed82b976ec7e0c4495ad6f1e79bf4d91b3740255063099d61cd9b61c57e714fdb49e861bbdc90819087132090ddda03b2ab5e5bf02e31f4ab291c45c0010105da2bd1fd56bf50c446ca5380e9ce4e9292af104dc83a5b7ca19c09141a316f8e299494c9d08870d8e9872de55183cdc2013f760fbbfbc8036c5e2ea0cbabaed778baa2c93a2bd09a2801c991e4c716c387fb2842ba72fb02eb28857e966c7bea8c5987a39c0b30e7637e51600a933d69a5f61d54e38d6a1a8aac0fdcebc684815415da5730dc3083d77455ad4d6e85387b5c31c6362daeb5f0d7266d95120a290df3fe744f18806165607c1ef4aee9d45ae50d74e6f2853d018283957472c9df914e02a7f2cfa03722ec3d93f9a30a4a533041ebd933ae979556c1ea31a8052996db189c7de62071e64a33f08021009578e94294e387f5a123e22d860e57b43a44f1c943c86c50f34e92ce050f87c75b88df892f71954d2bd4aa94c6de73128ee19a24965b13308e57b832c0cd20603d05c301380d6bb1eefaf55787fdfccc24ba6ea9bf6c5700fcc2af9f654e7480688ba7866be6df7915dc891c5c9b0a49802494b242c0e85017768f3bcf2a43625b19a91ef0fa19d0bfa12e405ec0d8fe8d24c4aa8d4071f0296a5d0865879994172e1fb816432f4aab77a3a371f8e9705d0e531d032207001d9a38a8c7ded6ee330d87ca5710441ee5e9781ed7588b2da4bc05831cd89f10b89d60fd602110fd79662d33f93aa6ba03e8d471d6857a533e025730b0412e20c5d5d1b841dbec2a82c4fa70dd39d9e0b502992a996f618b6bfea69a7649faa0a62de4b99312ad1ac32c1f9e7f1f178eeaa946ac5722e2073e179ae9fc72389001b4d2dcb247d932f71ca3303b04a9e4820cbd76d3ae1f1f2a1fae69cc7568400aa0a293d2784e97c041c262ad8d06a76c5c0329509a04c2ef99017a90bf91a06"]
}

**Comment by fluffypony** [comment]
Please don't use the HTTP interface. It's NOT an RPC interface for general use, it's for daemon <-> wallet communication, and is being replaced. We won't support the deprecated HTTP interface, although the JSON RPC API will remain supported even in its current form for quite some time.
