### ISSUE TITLE
bitmonerod doesn't exit gracefully.

### ISSUE THREAD

**Issue by oranjuice** [monero-project/bitmonero#223]
When I enter "exit", it sometimes gets stuck at
"Stop signal sent"
and sometimes at "Node stopped".

I usually have to kill the process and free the ports myself.

**Comment by fluffypony** [comment]
@tewinget is this fixed in https://github.com/monero-project/bitmonero/pull/245 do you think?

**Comment by tewinget** [comment]
Technically yes, but smooth raised a couple concerns about that pr last
night.  Needs further discussion.

**Comment by fluffypony** [comment]
Mostly fixed, will need to watch to see if it continues to occur
