### ISSUE TITLE
LMDB segfault

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#224]
log level 1 output:

http://pastebin.com/TECzyUkX

backtrace

http://pastebin.com/22Dtpp6v

i did do a system update while running the daemon that requested a restart. I'll try restarting it tomorrow to debug.

**Comment by Gingeropolous** [comment]
it restarted fine. ran overnight fine.

**Comment by fluffypony** [comment]
Fixed in DB branch
