### ISSUE TITLE
bitmonerod Does not accept non-lowercase command input

### ISSUE THREAD

**Issue by Idyllei** [monero-project/bitmonero#225]
When entering a CAPS or MiXeD CaSe command to bitmonerod (such as: "sAVE"), you receive an error such as: "unknown command: sAVE".

Recommended to change the case of all input to lowercase in order to improve user experience and ease of use. (This may also be seen as a flexibility increase).

![image](https://cloud.githubusercontent.com/assets/8077451/6176616/4e771b8a-b2ce-11e4-8759-b515488306cd.png)

**Comment by fluffypony** [comment]
fixed
