### ISSUE TITLE
database build SIGABRT

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#227]
Log Level 1 output:
http://pastebin.com/4AdUnESG

gdb tb:
http://pastebin.com/54zYH9rf

daemon was just sittin and doin its thing, also mining on 1 core. 

I woke up to a sigabrt.

**Comment by Gingeropolous** [comment]
tried to restart within gdb, didn't work. Then I couldn't restart because there were things running ... didn't copy the notification. Ended up killing the power (take THAT SSD!!!) in order to reboot it.

**Comment by fluffypony** [comment]
Fixed in upstream
