### ISSUE TITLE
Ignore enforce-dns-checkpoints on testnet

### ISSUE THREAD

**Issue by sammy007** [monero-project/bitmonero#232]
This option screwed my testnet sync. Should be ignored while running daemon with --testnet option.

**Comment by fluffypony** [comment]
This is on @tewinget's ultra-critical-extremely-urgent list of things to fix, but since it's possibly fixed in daemonize he's fixing that first and then this should be a knock-on fix

**Comment by fluffypony** [comment]
Fixed in daemonize
