### ISSUE TITLE
rcp-bind bitmonerod crashes with too many open files.

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#240]
Reported by TheKoziTwo:

Problem: Daemon server works for a day or so before getting this error multiple times and shutting down:
[1426196083] libunbound[28839:0] error: can't create socket: Too many open files

https://bitcointalk.org/index.php?topic=652305.msg10755422#msg10755422
http://pastebin.com/raw.php?i=Q7hrxDZz

**Comment by cornfeedhobo** [comment]
ACK. same issue. Will update in a day or two once it's been running a while again.

**Comment by fluffypony** [comment]
Fixed, will reopen if it occurs again
