### ISSUE TITLE
cmake miniupnpc filename case mismatch

### ISSUE THREAD

**Issue by meshpoint** [monero-project/bitmonero#246]
CMake 3.2.1 cannot find shared miniupnpc when building on a case-sensitive filesystem.

>CMake Warning at external/CMakeLists.txt:38 (find_package):
>  By not providing "FindMiniUpnpc.cmake" in CMAKE_MODULE_PATH this project
>  has asked CMake to find a package configuration file provided by
>  "MiniUpnpc", but CMake did not find one.

    find_package(MiniUpnpc QUIET)
       cmake/FindMiniupnpc.cmake

**Comment by fluffypony** [comment]
Nice catch - would you like to submit a fix via PR so you get credit for it? You can either rename the .cmake file or change the line in external/CMakeLists.txt, there's no knock-on effect for either and there's no preference for one route over another.

**Comment by meshpoint** [comment]
Other projects seem to spell it FindMiniupnpc.cmake
