### ISSUE TITLE
Seed nodes are down

### ISSUE THREAD

**Issue by u38** [monero-project/bitmonero#250]
Looks like all seed nodes aren't wokring. Can't synchronize from scratch.

**Comment by u38** [comment]
v0.8.8.6 works. With seed nodes taken from v0.8.8.6 master branch also works. Looks like seed nodes list in master contains only dead nodes.

**Comment by fluffypony** [comment]
The hardcoded seed list isn't used unless DNS seed nodes fail, which doesn't seem to be the case.
