### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#253]
Simplewallet checks the transfer string to see if there's a payment ID. If there's not, it displays "You are currently sending this payment without a payment ID. The recipient will not be able to identify that you have sent this payment. Would you like to add a payment ID?"

yes/no

"Would you like to add a random payment ID, or encode a message in hexadecimal? (limited to 32 characters)"

random / encode

random -> inserts random payment ID, executes transaction

Encode ->

"Please enter your message. Your message will be clipped at 32 characters or padded with 0's to reach 32 characters"

User enters message, hits return, executes transaction.

**Comment by tewinget** [comment]
This seems like a cool idea, but more geared toward a GUI setup than the
cli.

On Fri, Apr 3, 2015 at 7:40 AM, Gingeropolous <notifications@github.com>
wrote:

> Simplewallet checks the transfer string to see if there's a payment ID. If
> there's not, it displays "You are currently sending this payment without a
> payment ID. The recipient will not be able to identify that you have sent
> this payment. Would you like to add a payment ID?"
>
> yes/no
>
> "Would you like to add a random payment ID, or encode a message in
> hexadecimal? (limited to 32 characters)"
>
> random / encode
>
> random -> inserts random payment ID, executes transaction
>
> Encode ->
>
> "Please enter your message. Your message will be clipped at 32 characters
> or padded with 0's to reach 32 characters"
>
> User enters message, hits return, executes transaction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monero-project/bitmonero/issues/253>.
>



-- 
Thomas Winget
Computer Engineering
Purdue University '12

**Comment by 49kazuki** [comment]
no obtrusive msg boxes like that pls, some of us actually know what they are doing, a bold red-lettered warning on the payID box in the GUI would suffice.

**Comment by Gingeropolous** [comment]
well, until this is implemented somehow, newbies are just going to continue losing their funds. 

Maybe a seperate, modified wallet package then called NoobWallet

**Comment by sammy007** [comment]
Maybe it's good idea to introduce --expert option and make warning by default in normal mode, experts can create an alias in Unix-like system or .cmd file with --expect option to avoid warnings. In rpc server mode --expert should be forced indeed.

**Comment by generalizethis** [comment]
A check box (check if you do not want to see this message again) could work also. One time annoyance  is better than one time losing all their funds

**Comment by iamsmooth** [comment]
seems largely addressed by integrated addresses

**Comment by fluffypony** [comment]
Agreed - closing due to integrated addresses
