### ISSUE TITLE
The official binaries (v0.8.8.6) for Mac don't work on Mac OS X 10.9 (Mavericks)

### ISSUE THREAD

**Issue by Jojatekok** [monero-project/bitmonero#254]
I've been browsing through several websites, and it seems that the

    -mmacosx-version-min [version]

compiler flag is suggested.

**Comment by fluffypony** [comment]
https://bitcointalk.org/index.php?topic=583449.msg10963108#msg10963108

> There's a bug introduced into the cmake in 0.8.8.6 that broke static builds. This is fixed in head. On OS X you can either wait for 0.8.8.7 RC1 to be tagged and released (after today's mega-merge it's just bug squashing and minor bits before blockchainDB gets merged in), or just use Homebrew to install the dependencies and follow the build instructions in the README (this is not as daunting as it sounds, especially if you ocassionalky use the command-line).

So nothing to do with additional compiler flags:)
