### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#266]
This is on my machine that has faithfully been running tewinget's LMDB branch for over a month

http://pastebin.com/TFiJD7ki

**Comment by Gingeropolous** [comment]
Well, now its kicking out this:

-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Could not find miniupnp
-- Using miniupnpc from local source tree (/external/miniupnpc)
-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 64-bit LMDB from source tree
-- Could not find Berkeley DB >= 4.1 (missing:  BERKELEY_DB_INCLUDE_DIR BERKELEY_DB_LIBRARIES)
CMake Error at external/db_drivers/CMakeLists.txt:41 (add_subdirectory):
  add_subdirectory given source "libdb" which is not an existing directory.


-- BerkeleyDB not found, building from src tree
-- Enabling AES support
-- Found Git: /usr/bin/git
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY)
Doxygen: graphviz not found - graphs disabled
-- Configuring incomplete, errors occurred!
See also "/home/e5405/bitmonero_latest/bitmonero/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/e5405/bitmonero_latest/bitmonero/build/release/CMakeFiles/CMakeError.log".
make: *** [release-all] Error 1
e5405@e5405-G31M-ES2L:~/bitmonero_latest/bitmonero$

**Comment by fluffypony** [comment]
You need to install libgtest and libdb-dev / libdb++-dev

**Comment by Gingeropolous** [comment]
We figured it out:

totally copied this into the thing and then forgot to hit comment. 

<warptangent> CMake Error at external/db_drivers/CMakeLists.txt:41 (add_subdirectory)
<warptangent> that might be the main error
<warptangent> yeah
<warptangent> there is no dir for libdb
<warptangent> others wouldn't see the error if they have a system-wide berkeley db already
<warptangent> if you install berkeleydb for ubuntu, that may let it compile
<gingeropolous> but i don't need berkeley db...
<warptangent> I know
<warptangent> but they added it as a supported db compiled in anyway
<gingeropolous> cool, its working.
<warptangent> it won't run with bdb as the driver unless specified through a runtime option
<warptangent> good
<gingeropolous> ah, ok. so basically to maximize the compatability of the resulting binary
<warptangent> yes
<warptangent> bdb is common enough on systems that it probably was thought as reasonable to include in the default compile
<warptangent> if it's not found on the system already, however, the makefiles look for the bdb library code within bitmonero (in the external/ files, which is also where lmdb lives)
<warptangent> but bdb wasn't added to external/ yet. so the makefile fails
<gingeropolous> ah

**Comment by Gingeropolous** [comment]
hardware error?

http://pastebin.com/c2pPN6Wj

**Comment by Gingeropolous** [comment]
Finally built. Ended up getting a fresh clone from master, and it built.  Yay.
