### ISSUE TITLE
Mac binary problem illegal instruction 4

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#271]
on the #monero channel. 

<Almo> hi! I get Illegal instruction: 4 when trying to run simplewallet on my OSX machine
<Gingeropolous> hrm
<Gingeropolous> is this the latest build or the stable binary?
<Almo> https://downloads.getmonero.org/mac64
<Almo> from there
<Almo> that should be the stable binary, I think
<Gingeropolous> yeah
<Almo> I'm running MAvericks on a 2013 trashcan model
<Gingeropolous> im not a mac user - i've seen some people mention there's some quirky things with macs
<Almo> StackOverflow says that Illegal Instruction 4 often means it was compiled for an OS more advanced than what you have
<Almo> which could mean it was made with Yosemite
<Gingeropolous> ah
<Gingeropolous> can you build from source?
<Almo> I have the tools, I could try

**Comment by fluffypony** [comment]
Known issue, will be fixed in the next tagged release
