### ISSUE TITLE
Blockchain exporter config change didn't make

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#276]
http://pastebin.com/HQzVpi8Y

What I did:

in my existing bitmonero, went in and modified blockchain_export.h according to the instructions. Saved.

Went back to root directory of source, typed in make. Got the above output.

Controlled by reverting the code to original setting, and it compiled fine.

**Comment by warptangent** [comment]
Thanks for raising this. blockchain_export hadn't been updated yet to reflect changes in where BlockchainDB is instantiated.

Fixed in PR 277.
