### ISSUE TITLE
bitmonerod crashes with "too many open files" message (+core dump)

### ISSUE THREAD

**Issue by antanst** [monero-project/bitmonero#278]
After a few days running in my Linux machine, bitmonerod consistently crashes. 

I compiled it at commit 41f0a8fe4d87a0c58dcc60917eedaa6315fb30b8 with [this](https://github.com/monero-project/bitmonero/pull/277/files) additional patch (unrelated but I thought I should mention it).

```
# uname -a
Linux snf-627174 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

bitmonerod startup parameters:

```--limit-rate=2048 --limit-rate-up=2048 --limit-rate-down=2048```

Last few relevant lines of output of bitmonerod before crash:

```
2015-May-05 00:18:36.058752 [P2P9][46.148.140.72:44054 INC] SYNCHRONIZED OK
[warn] epoll_create: Too many open files
[err] evsig_init: socketpair: Too many open files
[warn] epoll_create: Too many open files
[err] evsig_init: socketpair: Too many open files
*** Error in './bitmonerod': double free or corruption (fasttop): 0x0000000002835a90 ***
Aborted (core dumped)
```

Core dump is [here](http://83.212.102.247/core).

**Comment by moneromooo-monero** [comment]
That's fixed a while back. Can you check if it happens again with current master ?

**Comment by fluffypony** [comment]
Fixed
