### ISSUE TITLE
error adding block

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#295]
I just did a git pull, compiled, running on mainnet, got this:

2015-May-29 17:38:19.896276 [P2P3][78.194.26.60:18080 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=200, txs.size()=0requested blocks count=200 / 200
2015-May-29 17:38:20.724617 [P2P8][217.23.2.242:18080 OUT]Sync data returned unknown top block: 583974 -> 585310 [1336 blocks (0 days) behind]
SYNCHRONIZATION started
2015-May-29 17:38:21.725372 [P2P9][83.212.114.252:18080 OUT]Sync data returned unknown top block: 583974 -> 585310 [1336 blocks (0 days) behind]
SYNCHRONIZATION started
2015-May-29 17:38:22.157302 [P2P6][61.90.204.244:18080 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 200
2015-May-29 17:38:22.888067 [P2P6]Failed to add tx blob to db transaction
2015-May-29 17:38:22.888360 [P2P6]ERROR /home/e5405/bitmonero_latest2/bitmonero/src/cryptonote_core/blockchain.cpp:2195 Error adding block with hash: <094397ace0327d4fc01146fb24acc5739008db5915025ef7209da0b619de15a9> to blockchain, what = Failed to add tx blob to db transaction
2015-May-29 17:38:23.631213 [P2P3][217.23.2.242:18080 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=200, txs.size()=0requested blocks count=200 / 200
2015-May-29 17:38:25.270475 [P2P6][80.71.13.36:18080 OUT]Sync data returned unknown top block: 583974 -> 585310 [1336 blocks (0 days) behind]
SYNCHRONIZATION started
2015-May-29 17:38:28.722489 [P2P9][94.23.55.211:18080 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 200
2015-May-29 17:38:29.456353 [P2P9]Failed to add tx blob to db transaction

**Comment by Gingeropolous** [comment]
and it just keeps on doing it. Its stuck on that block. 

I've tried reboot and clearing out the p2pstate.bin and poolstate.bin, nothing changed.

**Comment by warptangent** [comment]
Thanks for this.
Fixed in #297.
