### ISSUE TITLE
On mac OSX 10.10.3 I get illegal hardware instruction when trying to run bitmonerod

### ISSUE THREAD

**Issue by gweedobtc** [monero-project/bitmonero#319]
I am using version x64.v0-8-8-6
     % ./bitmonerod 
     [1]    62308 illegal hardware instruction  ./bitmonerod

**Comment by fluffypony** [comment]
When compiling?

**Comment by gweedobtc** [comment]
Nope when just trying to run it

**Comment by fluffypony** [comment]
Fixed in 0.9
