### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#356]
So I'm going through the cold wallet instructions, and copy linux simplewallet bins onto the flashdrive etc. Also download the libboost1.55-dev package and put that on the drive.

Boot into the live USB. Install libboost 1.55. Run simplewallet. Get this:

> ubuntu@lubuntu:~/Desktop$ ./simplewallet 
./simplewallet: error while loading shared libraries: libboost_date_time.so.1.55.0: cannot open shared object file: No such file or directory
lubuntu@lubuntu:~/Desktop$ 

I reboot, that fixes nothing. 

Then I think its because i didn't use apt-get, so I try apt-get install libboost1.55, tells me I already have it. 

I'm going to try one more reboot. Then I'll just make my tutorial video for how to compile head.

**Comment by warptangent** [comment]
It looks like you need libboost-date-time1.55 too:
Try
`apt-get install libboost-date-time1.55`

**Comment by Gingeropolous** [comment]
warptangent, yah know, for some reason i thought libboost dev woulda had date time in it.

**Comment by Gingeropolous** [comment]
old binaries. bah.
