### ISSUE TITLE
Crypto Kingdom synopsis and links for External Project's page @ getmonero.org

### ISSUE THREAD

**Issue by generalizethis** [monero-project/bitmonero#398]
Crypto Kingdom is MMORPG set in a sandbox with a real economy. You can make trades, invest in game assets, buy lots for development, develop new technologies or drink to your heart's content. It's Monopoly, Civilization and Second Life rolled into one game with elements of social networking.

BCT Forum: https://bitcointalk.org/index.php?topic=819073.0

Reddit: https://www.reddit.com/r/cryptokingdom/

Game: http://188.166.24.181/

**Comment by fluffypony** [comment]
Thanks! The Monero Site repo is here: https://github.com/monero-project/monero-site - if you could open the issue there I'll make the necessary adjustments:)
