### ISSUE TITLE
Build of development branch fails on OSX El Capitan

### ISSUE THREAD

**Issue by antanst** [monero-project/bitmonero#600]
Build of development branch fails on OSX El Capitan.

master branch compiles fine. ZMQ installed version is stable 3.0.2.

Build log:

http://fpaste.org/306862/19024001/

**Comment by radfish** [comment]
fpaste is gone, that's why relevant content should be attached directly to bug reports instead of a pastebin.

There's another ticket for OSX build, so this one can be closed.

**Comment by fluffypony** [comment]
Dev branch is nuked, so closing this
