### ISSUE TITLE
simplewallet reports 'splitting' into 1 transactions

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#667]
https://bitcointalk.org/index.php?topic=583449.msg13887366#msg13887366

[quote author=medusa13 link=topic=583449.msg13887366#msg13887366 date=1455500384]
small cosmetics, dont know if it matters now that the GUI is coming..

still:

[code]Your transaction needs to be split into 1 transactions.  This will result in a transaction fee being applied to each transaction, for a total fee of 0.210000000000.  Is this okay?  (Y/Yes/N/No)y
Money successfully sent, transaction <42921fe1371fabb39d51f1e54580c4fefcae0e64cb2a4f04d481aa1b0b64c86d>[/code]

with 9.1 official

cheers and hodl 
[/quote]

**Comment by moneromooo-monero** [comment]
Fixed, not sure how to tell github.
