### ISSUE TITLE
Add ability to sweep a wallet's balance

### ISSUE THREAD

**Issue by fluffypony** [monero-project/bitmonero#668]
Currently it's extremely difficult to sweep a wallet due to the fee only being able to be computed when the transaction is built, so it becomes a bit of trial-and-error. We should add a command that lets you sweep the balance of a wallet to a destination, and it takes care of splitting / fees / etc.

This may be a little complex due to the inability to chain Monero transactions (ie. you have to wait for change to "clear" before you can send the next transaction), so any split should be exact and shouldn't be reliant on change.

**Comment by moneromooo-monero** [comment]
Such a command would have to spend two different types of txes: one with mixin 0 for unmixable things, and one with mixin 2 for the rest. sweep_unmixable should not create change, the other should be some variation on transfer_new to avoid creating change in split txes.

**Comment by moneromooo-monero** [comment]
Done in https://github.com/monero-project/bitmonero/pull/815, though that only does a single (possibly split) tx. The user can sweep_unmixable first if needed.

**Comment by fluffypony** [comment]
Fixed

**Comment by greatwolf** [comment]
Just to clarify, can `sweep_unmixable` be use to consolidate dust transactions? For example, early implementations of node-cryptonote-pool used by many mining pools use to send a lot of dust payout transactions frequently until they finally fixed it. Can mined dust amounts from that period be consolidated with `sweep_unmixable`? Any caveats and consequences to be aware of when doing this?

**Comment by fluffypony** [comment]
@greatwolf ```sweep_unmixable``` only works for old dust amounts that aren't quantised, eg. an output of 0.003279123. It won't help for very small quantised amounts, eg. an output of 0.000000003 XMR.
