### ISSUE TITLE
simplewallet --generate-new-wallet bug

### ISSUE THREAD

**Issue by fluffypony** [monero-project/bitmonero#691]
Per @petertodd:

> ```simplewallet --generate-new-wallet``` doesn't save to ```<address>.wallet``` like the help text says it does

**Comment by petertodd** [comment]
Well, I think it'd be good if 'simeplewallet --generate-new-wallet'
created a new wallet of the form <addr>.wallet like the help text says
it does. But yeah, changing the help text would be a way to fix this
issue too.

> ```simplewallet --generate-new-wallet```
> returns the error message
> ```Failed to parse arguments: the required argument for option '--generate-new-wallet' is missing```
> 
> For clarity's sake, is the bug that the help is wrong or that the default behavior is not working?
> 
> i.e. Should
> ```simeplewallet --generate-new-wallet```
> be just as valid as
> ```simplewallet --generate-new-wallet arg```
> or is it correct that it forces you to name the wallet?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/monero-project/bitmonero/issues/691#issuecomment-191393271

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org
000000000000000000f755631f059a7cbbefae9e2d3783197e824154dd926639
