### ISSUE TITLE
simplewallet: When rpc-bind-port is specified, password-file does not work

### ISSUE THREAD

**Issue by Aerbax** [monero-project/bitmonero#722]
When making simplewallet non-interactive via the rpc-bind-ip and rpc-bind-port, --password-file will not read the appropriate file.  However, --password does - but that exposes the password in plain text when the process tree is inspected.

Just specifying rpc-bind-ip is fine...the password file is read appropriately.  When rpc-bind-port is added, the password-file is not read and simplewallet gives the error: "ERROR /DISTRIBUTION-BUILD/src/simplewallet/simplewallet.cpp:2561 Wallet password not set."

I am running "Monero 'Hydrogen Helix' (v0.9.1.0-release)" on x64 on Debian.  The binaries are those on the getmonero website.

**Comment by jwinterm** [comment]
Confirmed same behavior on Windows 10 using same release here.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/734
