### ISSUE TITLE
tx splitting likely resulting in uselessly small outputs

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#754]
This tx looks like a portion of a split, and the .______666666 amount results in both useless payment and fee outputs.

http://moneroblocks.info/tx/ab3607ce839614131de594bd5eaaba9910bcb68ebebedae9a396722ed0ea5e09

When splitting probably should do something other than just divide by N to calculate the target size for each piece. For example repeatedly: divide by number of remaining pieces, truncate to desired precision, and subtract from remaining total.

**Comment by iamsmooth** [comment]
The other 2 portions of the split are in adjacent blocks

**Comment by moneromooo-monero** [comment]
That's one of the things that transfer_new changes.

**Comment by fluffypony** [comment]
Can this be closed?

**Comment by iamsmooth** [comment]
Not unless we are completely replacing 'transfer' with 'transfer_new' which seemed in some way undesirable when discussed in the past (I don't remember the details). We can consider this an issue with regular 'transfer' exclusively.

**Comment by iamsmooth** [comment]
will become irrelevant with ringct, so closing
