### ISSUE TITLE
PR #756: handle bad / incorrect JSON types

### ISSUE THREAD

**Issue by fluffypony** [monero-project/bitmonero#760]
Per https://github.com/monero-project/bitmonero/pull/756#issuecomment-201109722 and the comment thereafter

> "Note that, RapidJSON does not automatically convert values between JSON types. If a value is a string, it is invalid to call GetInt(), for example. In debug mode it will fail an assertion. In release mode, the behavior is undefined."

Since this is unbound user input we need to sanitise and check before acting on any particular input.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/769

**Comment by fluffypony** [comment]
Closed via #769
