### ISSUE TITLE
simplewallet: stdout is not terminal output

### ISSUE THREAD

**Issue by fanatid** [monero-project/bitmonero#776]
If run `simplewallet` when `stdout` and `stderr` is not terminal outputs (redirect to file for example), log messages is not flushed:

```
$ ./simplewallet --wallet-file 1 --password 1 --rpc-bind-port 18082 >stdout.log 2>&1
^Z
[1]+  Stopped
$ cat stdout.log
Creating the logger system
Monero 'Hydrogen Helix' (v0.9.3.0-0ee87e6)
Logging at log level 0 to /home/kirill/tmp/simplewallet.log
$ fg
^C
$ cat stdout.log
Creating the logger system
Monero 'Hydrogen Helix' (v0.9.3.0-0ee87e6)
Logging at log level 0 to /home/kirill/tmp/simplewallet.log
2016-Mar-29 22:45:31.051405 Loading wallet...
2016-Mar-29 22:45:31.095404 Loaded wallet keys file, with public address: 4AQEqg4oDFw6YM6L86CLvX26etwTKvN7gaN1fXzs18bm7TyEbpxYrHadLDY2n98m8z3zFMeg3FTaLHmJtGdJG7dSF31ny3q
2016-Mar-29 22:45:34.023976 Loaded ok
...
```

but without redirected, all ok:
```
$ ./simplewallet --wallet-file 1 --password 1 --rpc-bind-port 18082
Creating the logger system
Monero 'Hydrogen Helix' (v0.9.3.0-0ee87e6)
Logging at log level 0 to /home/kirill/tmp/simplewallet.log
2016-Mar-29 21:57:40.090158 Loading wallet...
2016-Mar-29 21:57:40.132003 Loaded wallet keys file, with public address: 4AQEqg4oDFw6YM6L86CLvX26etwTKvN7gaN1fXzs18bm7TyEbpxYrHadLDY2n98m8z3zFMeg3FTaLHmJtGdJG7dSF31ny3q
2016-Mar-29 21:57:43.112484 Loaded ok
...
```

**Comment by fanatid** [comment]
@tewinget yes, you interpreting right
let say I press Ctrl-Z after 10s, loading wallet takes ~2s (for remote daemon)

**Comment by tewinget** [comment]
Interesting.

On Tue, Mar 29, 2016 at 4:12 PM, Kirill Fomichev <notifications@github.com>
wrote:

> @tewinget <https://github.com/tewinget> yes, you interpreting right
> let say I press Ctrl-Z after 10s, loading wallet takes ~2s (for remote
> daemon)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/monero-project/bitmonero/issues/776#issuecomment-203079343>
>



-- 
Thomas Winget
Computer Engineering
Purdue University '12

**Comment by antanst** [comment]
I stumbled upon this issue some time ago when I tried to parse simplewallet's output. I ended reading the logs instead. There's probably some kind of buffering going on.

**Comment by moneromooo-monero** [comment]
Probably just needs a call to setvbuf to make it line buffered.

**Comment by moneromooo-monero** [comment]
There doesn't seem to be an equivalent to setvbuf that allows line buffering, so I just flush cout.
https://github.com/monero-project/bitmonero/pull/787

**Comment by fluffypony** [comment]
Fixed
