### ISSUE TITLE
Wallet file inconsistencies

### ISSUE THREAD

**Issue by arnuschky** [monero-project/bitmonero#793]
I deleted my `walletname.bin` in order to rescan my wallet when upgrading to 0.9.2.

 * After rescanning and terminating simplewallet, I noticed that the wallet wasn't saved. I had to manually enter `save` after rescanning in order to make the change permanent. Seems a bug to me.
 * The new db file is called only `walletname` rather than `walletname.bin`. Is that intentional?
 * The new file is world-readable. Urgh.

**Comment by moneromooo-monero** [comment]
Did you kill simplewallet, or exit it with exit ?

The wallet is called whatever you call it. If your keys file is named walletname.bin.keys, the cache should be walletname.bin. If your keys file is named walletname.keys, the cache should be walletname.

**Comment by arnuschky** [comment]
Ok for the naming part then. Didn't understand your other comment. I tried both: `exit` and ctrl-c when running in RPC server mode.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/801 fixes the permissions issue (except on windows, which is always the weird one, so will need someone with Windows to fill in the blanks).

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/803 fixes the saving in RPC mode

**Comment by fluffypony** [comment]
Fixed, per @moneromooo-monero
