### ISSUE TITLE
UNBOUND_LIBRARIES error building on Ubuntu 14.04

### ISSUE THREAD

**Issue by laanwj** [monero-project/bitmonero#836]
I get the following error running cmake on Ubuntu 14.04 (cmake is version 2.8.12.2):
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
UNBOUND_LIBRARIES
    linked by target "unit_tests" in directory /home/ubuntu/bitmonero/tests/unit_tests
```
Both `v0.9.4` and `master` suffer from this.

According to `git bisect` this broke with commit 34957fcbb97052532b8f16f7cb2bd637904e047b:
```
34957fcbb97052532b8f16f7cb2bd637904e047b is the first bad commit
commit 34957fcbb97052532b8f16f7cb2bd637904e047b
Author: moneromooo-monero <moneromooo-monero@users.noreply.github.com>
Date:   Tue Mar 29 17:56:42 2016 +0100

    tests: add test for needed OpenSSL algorithms in unbound
    
    These can be compiled out of libunbound, leading to failure
    to check DNSSEC validity.

:040000 040000 62634aa5c46564ec73045609a54073f7c6e94725 1abfe5464ee2743d47d8025394a470e937fe2e79 M      tests
```

I see that the problem was also reported here on bitcoin talk: https://bitcointalk.org/index.php?topic=652305.msg14613563#msg14613563

Building without tests works around this problem.

**Comment by dEBRUYNE-1** [comment]
Quoting @hyc here:

>Yes, tests got broken in a recent commit. You should use the v0.9.4 tag instead of master. Or you can merge this patch into your build tree: https://github.com/monero-project/bitmonero/pull/811

Source: https://www.reddit.com/r/Monero/comments/4gakjp/maam_13_monero_ask_anything_monday/d2gvq8o?context=3

**Comment by laanwj** [comment]
Thanks, but that indeed seems like a different issue.
Also #811 is a change in the source code, as cmake complains I'd expect to fix this would need a change in the cmake file.

**Comment by dEBRUYNE-1** [comment]
I see, after reading the thread these other "fixes" were suggested:

@hyc suggested:

>Pretty sure that UNBOUND problem was introduced *after* the 0.9.4 release. Quick workaround is to edit build/release/CMakeCache.txt and change "BUILD_TESTS" from "ON" to "OFF" then do "make rebuild_cache" and then "make" again.

@iamsmooth suggested:

>Maybe try compiling 0.9.4 itself rather than possibly-unstable changes after that

>git checkout v0.9.4
>make clean (this will wipe out the 'build' subdirectory; make sure you don't have any wallets in there)
>make

P.S. I've forwarded the issue to @moneromooo-monero as well.

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/bitmonero/pull/831

**Comment by hyc** [comment]
Specifically, in commit https://github.com/monero-project/bitmonero/pull/831/commits/7a663873cebd135eb32ca68ad1f05873e29248a9

**Comment by laanwj** [comment]
Can confirm that #831 fixes this issue.

**Comment by fluffypony** [comment]
Fixed
