### ISSUE TITLE
restricted rpc modifications

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#839]
```MAP_URI_AUTO_JON2_IF("/mining_status", on_mining_status,)```

Does this need to be restricted?

```  MAP_JON_RPC_WE("flush_txpool",           on_flush_txpool,               COMMAND_RPC_FLUSH_TRANSACTION_POOL)```

should probably be restricted.

**Comment by iamsmooth** [comment]
I think mining_status should stay restricted, just in general because it isn't a service that is useful for most public nodes to provide but also specifically because it gives out your address.

Agree flush_txpool should definitely be restricted.

**Comment by iamsmooth** [comment]
#843
