### ISSUE TITLE
json_rpc: method getblock returns invalid json

### ISSUE THREAD

**Issue by FelixWeis** [monero-project/bitmonero#841]
The JSON result contains a section `result.blob` which is raw binary. This is obviously not allowed in normal JSON and should be encoded in hex.

**Comment by FelixWeis** [comment]
to replicate this behaviour:

    curl -v -X POST 127.0.0.1:18081/json_rpc -d '{"id":"0","jsonrpc":"2.0","method":"getblock","params":{}}' | jq .

[jq](https://stedolan.github.io/jq/) is a JSON cli tool.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/863

The "json" field has an escaped string, which is not super useful either. I'll look to see if it can be set unescaped.

**Comment by moneromooo-monero** [comment]
In fact, I think adding this json field was a stupid idea. There doesn't seem to be a way to save it as is, and I'm realizing that it'd need to be re-parsed in order for it to work in code, so that probably explains why existing code did not include raw txes/blocks/etc.

**Comment by moneromooo-monero** [comment]
I've looked at properly displaying those as json, but AFAICT it's a differnet serialization system (KV_BEGIN_SERIALIZE_MAP vs BEGIN_SERIALIZE_OBJECT) and I got stopped at the boost::variant stuff. Any opinions on whether these dumps are worth spending time on ?

**Comment by fluffypony** [comment]
Fixed
