### ISSUE TITLE
boost_serialization_helper.h:108 Exception at [unserialize_obj_from_file], what=unsupported version

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/bitmonero#849]
just cloned repository, so:
Latest commit a837c9c  7 days ago

2016-May-24 06:58:14.717997 Initializing core...
2016-May-24 06:58:14.728190 ERROR /home/gbone/bitmonero_head/src/common/boost_serialization_helper.h:108 Exception at [unserialize_obj_from_file], what=unsupported version
2016-May-24 06:58:14.728349 Loading blockchain from folder /home/gbone/.bitmonero/lmdb ...

**Comment by moneroexamples** [comment]
What os?

**Comment by Gingeropolous** [comment]
gbone@gbone-therock:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Comment by Gingeropolous** [comment]
This issue has been fixed (somehow)
