### ISSUE TITLE
Can't build in Ubuntu 16.04 in Pine64 board (aarch64)

### ISSUE THREAD

**Issue by antanst** [monero-project/bitmonero#851]
`uname -a` output:

`Linux pine 3.10.65-7-pine64-longsleep #28 SMP PREEMPT Sat Apr 23 20:13:25 CEST 2016 aarch64 aarch64 aarch64 GNU/Linux`

`lscpu` output:

`Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
CPU max MHz:           1344.0000
CPU min MHz:           480.0000
`

Using `master` branch at commit `a837c9cb0feeb7c8c4e616df64cbf650e38355f7`

`make release` output here: [https://paste.fedoraproject.org/371009/](https://paste.fedoraproject.org/371009/)

**Comment by radfish** [comment]
On ARM: `cmake -DNO_AES=ON`

**Comment by osensei** [comment]
Maybe this can help? #830

**Comment by antanst** [comment]
I disable the AES flag as per #830, and then I stumble upon this error:

`[ 50%] Building CXX object contrib/otshell_utils/CMakeFiles/otshell_utils.dir/utils.cpp.o
c++: error: unrecognized command line option ‘-mfloat-abi=hard’
`

...which I've not yet managed to solve, even by following step by step the instructions from #380.

**Comment by radfish** [comment]
You should really regenerate the makefile with cmake:

```
cd bitmonerod
mkdir build
cd build
cmake -DNO_AES=ON ..
make
./bin/bitmonerod
```

It is incorrect to have the generated makefile committed in the repository. Hopefully this bug report will convince the devs to remove it.

**Comment by antanst** [comment]
I managed to compile it with your instructions. Thanks.

Mining currently nets the absurdly low amount of 5 (!) hashes / sec when mining with 4 threads :-)

**Comment by radfish** [comment]
This is off-topic to this issue report (which can be closed now, btw) and not related to mining, but I'm just curious did your node sync the blockchain without a hitch on pine64? What does 'bitmonerod status' say?

**Comment by antanst** [comment]
Yes, it synced successfully. I don't have access to the machine right now to tell you the exact output, but it's the "normal" status reply that I've seen on all other nodes I've set up.

**Comment by radfish** [comment]
@antanst Last question: how long did it take to sync (approx) and which GCC version did you use to build?

**Comment by antanst** [comment]
`gcc (Ubuntu/Linaro 5.3.1-14ubuntu2) 5.3.1 20160413`

It took a couple of days to sync. I'm guessing the bottleneck was the I/O, more specifically the Class 10 SD card I have in the Pine64.

`status` command output on a fresh start of bitmonerod:

`Height: 1060122/1060122 (100.0%) on mainnet, mining at 2 H/s, net hash 12.72 MH/s, v2, up to date, 6+0 connections`

**Comment by antanst** [comment]
Unless the developers have an issue with this, I'm reopening this bug and keeping it open until the project builds fine via the usual way just like in other architectures.

**Comment by radfish** [comment]
Thanks for details. It's absolutely that I/O is the bottleneck. I've been fighting with several issues that manifest as extremely excessive I/O to the point where the node stops working. The good news is that when the node correctly operates in steady state, it uses negligibly little I/O.

For fast syncs, you can sync on an armv7 machine (and in the future any machine) with faster storage and copy lmdb folder. I successfully used ARM server at scaleway.com for this purpose.

Yeah, to fix the current issue, cmake script needs to be updated to set the NO_AES for ARM. (I don't think per-architecture targets in the top-level makefile is a good approach, but the current target for ARM would need to be split into ARM 32 and ARM 64).

**Comment by radfish** [comment]
PR #877 was merged, so this can be closed. Should build with `make release` now.
