### ISSUE TITLE
get_payments Wallet RPC call allows for incorrect payment ID lengths

### ISSUE THREAD

**Issue by sheepman0** [monero-project/bitmonero#860]
Just discovered the get_payments call allows for a payment ID of 15/16/63/64 characters when presumably it should only allow 16/64 character payments ID's.

**Comment by moneroexamples** [comment]
dont they get paded to required length?

**Comment by sheepman0** [comment]
Surely if they did I should be able to use something other then just one character less then expected? For example a payment ID of 14 characters or less errors, it doesn't get padded.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/862

**Comment by fluffypony** [comment]
Fixed
