### ISSUE TITLE
max_out exceeded

### ISSUE THREAD

**Issue by ManfredKarrer** [monero-project/bitmonero#861]
I was missing incoming transactions to my wallet and got strange block heights (larger as on the explorer), so I deleted the data dir with the blockchain and started over again. After restart of bitmonerod (on Mac) i got that error: 
ERROR /DISTRIBUTION-BUILD/src/cryptonote_core/cryptonote_format_utils.cpp:148 max_out exceeded
It kept stuck for a while but then started syncing.

Edit: strange block heights -> was issues of blockexplorer (http://chainradar.com/xmr/blocks) on http://moneroblocks.info/ block height is like in bitmonerod.

**Comment by moneroexamples** [comment]
What do you mean by strange? Any exmaples?

**Comment by ManfredKarrer** [comment]
@moneroexamples The height was lower at the blockexplorer (http://chainradar.com/xmr/blocks) than as the one at the bitmonerod. But was not an issue of bitmonerod, but of chainradar.
Now after a new sync of the complete blockchain I have all expected transactions in my wallet visible.
Seems before there was something locked up in the blockchain DB.

**Comment by moneromooo-monero** [comment]
This can be ignored, and is fixed in master.
