### ISSUE TITLE
simplewallet rpc: Payment IDs are not included when sending to integrated addresses using rpc transfer method.

### ISSUE THREAD

**Issue by osensei** [monero-project/bitmonero#892]
What the title says.

When sending coins to an integrated address using the rpc transfer method, the coins will be sent to the standard address without the payment ID.

There seems to be some logic in simplewallet.cpp, that parses the integrated address and extracts the payment ID, that is not implemented on wallet_rpc_server.cpp

**Comment by moneromooo-monero** [comment]
Fixed in https://github.com/monero-project/bitmonero/pull/899

**Comment by osensei** [comment]
You da man!

I can confirm it works.

**Comment by luigi1111** [comment]
Fixed by #899
