### ISSUE TITLE
master fails to compile

### ISSUE THREAD

**Issue by schnerchi** [monero-project/bitmonero#901]
Am I the only one that can not compile git master? compiling tag v0.9.4 works.....

**Comment by schnerchi** [comment]
system : ubuntu 16.04 and mac osx 10.11.5

**Comment by moneromooo-monero** [comment]
At the risk of sounding obvious, a mention of the error would help.

**Comment by moneromooo-monero** [comment]
If it's something to do with an operator /= in boost, this got fixed yesterday.

**Comment by schnerchi** [comment]
sure, I was just wondering. Last time master would not compile it was "well" known...

info : http://pastebin.com/JiHc2V1E
error : http://pastebin.com/wW91MsC1

**Comment by radfish** [comment]
Duplicate of #871. There is a patch described there, you can try applying it.

**Comment by schnerchi** [comment]
pull #904 solves this issue. thanks!
