### ISSUE TITLE
bitmonerod release-static fails to build on macOS, stack_trace.cpp undefined ___real___cxa_throw

### ISSUE THREAD

**Issue by RaskaRuby** [monero-project/bitmonero#932]
Using OS X 11.6 (El Capitan) and Brew with these packages: 
boost cmake libevent miniupnpc pkgconfig

`[ 95%] Linking CXX executable ../../bin/bitmonerod Undefined symbols for architecture x86_64: "___real___cxa_throw", referenced from: ___wrap___cxa_throw in libcommon.a(stack_trace.cpp.o) ld: symbol(s) not found for architecture x86_64`

**Comment by radfish** [comment]
Try #934.
