### ISSUE TITLE
macOS: release builds fine, release-static does not

### ISSUE THREAD

**Issue by RaskaRuby** [monero-project/bitmonero#935]
Using OS X 11.6 (El Capitan) and Brew with these packages:
boost cmake libevent miniupnpc pkgconfig

`[ 86%] Building CXX object src/miner/CMakeFiles/simpleminer.dir/simpleminer.cpp.o
[ 87%] Linking CXX executable ../../bin/simpleminer
ld: unknown option: --wrap=__cxa_throw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/simpleminer] Error 1
make[2]: *** [src/miner/CMakeFiles/simpleminer.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release-static-64] Error 2
`

**Comment by radfish** [comment]
Try #937 please

**Comment by RaskaRuby** [comment]
Fixed by [#937](https://github.com/monero-project/bitmonero/pull/937
), master release-static built fine for me on macOS.
Thanks radfish!
