### ISSUE TITLE
OSX issues - Abort trap: 6

### ISSUE THREAD

**Issue by ManfredKarrer** [monero-project/bitmonero#942]
I get always an "Abort trap: 6" when running bitmonerod and simplewallet.
I installed a nightly build but its the same problem.

bitmonerod also logs:
2016-Jul-30 14:23:02.279945 [P2P8][93.81.51.138:59835 INC]Sync data returned unknown top block: 1102568 -> 1009962 [92606 blocks (-64 days) ahead] 

I tried a few times (with the older official download) to re-download the blockchain but without success.

Someone in the IRC recommended me a to set a flag, but forgot which one. 

I am on OSX  10.9.5.

**Comment by moneromooo-monero** [comment]
Add --max-concurrency 1

**Comment by ManfredKarrer** [comment]
was first working (SYNCHRONIZED OK) but then i got again the 
Sync data returned unknown top block: 1104056 -> 1009962 [94094 blocks (-65 days) ahead]

**Comment by radfish** [comment]
That warning is harmless. Use 'status' command to check the block number your node is at.

**Comment by ManfredKarrer** [comment]
ah ok. yeah seem the simplewallet works now again. thanks!
i think the log msg shoudl be changed, its confusing...
