### ISSUE TITLE
Rpcwallet crashes without leaving a clue behind while the daemon is initializing

### ISSUE THREAD

**Issue by Jojatekok** [monero-project/bitmonero#95]
The new rpcwallet simply exits (without leaving an error message behind) whether opened straight after the daemon: The daemon starts loading the blockchain, and that results in the rpcwallet closing. Please let the wallet check for the daemon's RPC port to be active, thus, indicating that it has already loaded the chain.

**Comment by fluffypony** [comment]
Fixed
