### ISSUE TITLE
Boost issue when trying to make

### ISSUE THREAD

**Issue by kirkins** [monero-project/bitmonero#957]
I'm trying to make monero on centos 7.2. I have boost installed but I get back this:
```

[red@datasci bitmonero]$ sudo make release-static-64
mkdir -p build/release
cd build/release && cmake -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Could not find libunwind (missing:  LIBUNWIND_INCLUDE_DIR LIBUNWIND_LIBRARIES) 
-- Stack trace on exception disabled
-- Could not find miniupnp
-- Using miniupnpc from local source tree for static build
-- Looking for libunbound
-- Using 64-bit LMDB from source tree
-- AES support enabled
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1096 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:451 (find_package)


CMake Error at CMakeLists.txt:45 (message):
  Could not find Boost libraries, please make sure you have installed
  Boost or libboost-all-dev (1.53 or 1.55+) or the equivalent
Call Stack (most recent call first):
  CMakeLists.txt:455 (die)


-- Configuring incomplete, errors occurred!

```

**Comment by anonimal** [comment]
>Unable to find the Boost header files.  Please set BOOST_ROOT to the root
directory containing Boost or BOOST_INCLUDEDIR to the directory containing
Boost's headers.

So, you can try something like this:
```bash
$ BOOST_ROOT=/usr/local/
$ export BOOST_ROOT
```
Replacing your ```BOOST_ROOT``` as appropriate, then running make again.

Does that work?

**Comment by kirkins** [comment]
I'm trying this based on what you said (/usr/include/boost seems to be where boost is located):

`BOOST_ROOT=/usr/include/boost
export BOOST_ROOT`

Getting the same results.

**Comment by guzzijones** [comment]
is /user/include part of your path?

**Comment by kirkins** [comment]
I think you mean '/user/include'. It wasn't in my path. I've since tried adding it and rebooted the server.

Still the same error.

**Comment by guzzijones** [comment]
If you are on linux it is /usr

Enviado con Aquamail para Android
http://www.aqua-mail.com


El 13 de agosto de 2016 4:33:36 PM kirkins <notifications@github.com> escribio:

**Comment by guzzijones** [comment]
I just had the same issue after installing a self compiled verison of boost.

I had to do:
export BOOST_ROOT=[path to boost root];   mine was /usr/local
make clean
make

for some reason cmake was remembering i previously had built with the 
system version of boost.

good luck

**Comment by guzzijones** [comment]
Is this issue closed?  
Did you try  
```
$ export BOOST_ROOT=/usr/local
$ make clean
$ make
```

**Comment by kirkins** [comment]
I gave up and switched back to debian so I'll close this.
