### ISSUE TITLE
make release error on macOS ElCap 10.11.6 in wallet2.cpp, "no member named 'default_random_engine'"

### ISSUE THREAD

**Issue by RaskaRuby** [monero-project/bitmonero#965]
Both 'make release' and 'make release-static' are giving this error now.
I'm using an up-to-date brew with 'boost cmake libevent miniupnpc pkgconfig'

[ 73%] Building CXX object src/wallet/CMakeFiles/wallet.dir/wallet2.cpp.o
/Users/cgrice/src/bitmonero/src/wallet/wallet2.cpp:2487:53: error: no member named 'default_random_engine' in namespace 'std'
      std::shuffle(order.begin(), order.end(), std::default_random_engine(crypto::rand<unsigned>()));

**Comment by moneromooo-monero** [comment]
Is this fixed if you add this at the end of the include list in src/wallet/wallet2.cpp, near line 57 ?

#include <random>

**Comment by RaskaRuby** [comment]
What should be included? (I think your comment got chopped off)

**Comment by iDunk5400** [comment]
Yep, `#include <random>` fixes it in MSYS2 on Windows.

**Comment by RaskaRuby** [comment]
Me too. macOS builds fine  with release and release-static after adding `#include <random>` to wallet2.cpp

**Comment by moneroexamples** [comment]
The same on arch linux with gcc 6.1

**Comment by moneromooo-monero** [comment]
Sorry, something parses that as HTML I guess.
Thanks for reporting.

**Comment by RaskaRuby** [comment]
Fixed by the changes in [https://github.com/monero-project/bitmonero/pull/968](url)
Thanks for fixing!
