### ISSUE TITLE
Compile Error: Add pkg-config to dependencies #951

### ISSUE THREAD

**Issue by grummerd** [monero-project/bitmonero#969]
i'm on ubuntu 16.04.02 LTS

> $ make -j 4

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:52 (find_package_handle_standard_args)
  external/unbound/CMakeLists.txt:57 (find_package)
```

> dpkg -l | grep pkg-config

if returns nothing then

> sudo apt-get install pkg-config

Please add `pkg-config` as a dependency in readme.md docs

**Comment by radfish** [comment]
merged in #973

**Comment by radfish** [comment]
oh, this one is good to close, right?

**Comment by grummerd** [comment]
This one has been closed for at least one week. pkg-config dependency is in bitmonero and [moneroexamples](https://github.com/moneroexamples/compile-monero-09-on-ubuntu-16-04) docs 

Is not in the kovri docs yet. But as far as bitmonero is concerned this issue is closed

**Comment by anonimal** [comment]
Not required for kovri. Completely different project.
