### ISSUE TITLE
ARM: build fails due to ld segfaulting on checkpoints.dat

### ISSUE THREAD

**Issue by radfish** [monero-project/bitmonero#974]
```
cd /home/redfish/bitmonero-git/src/bitmonero/build/src/daemon && cd /home/redfish/bitmonero-git/src/bitmonero/src/daemon && cp ../blocks/checkpoints.dat blocks.dat && /usr/bin/ld -r -b binary -o /home/redfish/bitmonero-git/src/bitmonero/build/src/daemon/blocksdat.o blocks.dat && rm -f blocks.dat
```
The ld command segfaults even for the empty testnet_blocks.dat

The ld command succeeds on x86 (32bit). Sounds like an ld bug. Filing here, just for visibility:
```
$ touch foo.dat
$ /usr/bin/ld -r -b binary -o /tmp/foo.o foo.dat
Segmentation fault (core dumped)
```

GDB on ld:
```
(gdb) bt
#0  0xb6f2ca94 in ?? () from /usr/lib/libbfd-2.27.so
#1  0xb6f66ad0 in bfd_elf_final_link () from /usr/lib/libbfd-2.27.so
```

**Comment by radfish** [comment]
Workaround: use ld.gold instead of ld: `cmake -DCMAKE_LINKER=/usr/bin/ld.gold`

Sidenote: This CMAKE_LINKER var seems to affect only the linker invocations in the custom commands that deal with checkpoints.dat; all the rest is still linked with ld. So, the workaround has a minimal impact.

I will leave this issue open for a little while for visibility, then will close.

**Comment by NanoAkron** [comment]
Which ARM architecture?

**Comment by radfish** [comment]
armv7h

**Comment by radfish** [comment]
They patched it, should make it into next binutils release I guess:
http://lists.gnu.org/archive/html/bug-binutils/2016-08/msg00165.html
