### ISSUE TITLE
cmake fails when gtest is installed on the system

### ISSUE THREAD

**Issue by flounders** [monero-project/bitmonero#980]
Everytime I try running just `make` I keep getting this:

```
-- outfile location is /home/swilliams/builds/bitmonero/build/release/lib/libwallet_merged.a
CMake Error at tests/CMakeLists.txt:90 (set_property):
  set_property could not find TARGET gtest.  Perhaps it has not yet been
  created.


-- Configuring incomplete, errors occurred!
See also "/home/swilliams/builds/bitmonero/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/swilliams/builds/bitmonero/build/release/CMakeFiles/CMakeError.log".
```

Running `make debug` I was able to get a binary, but not with `make` by itself.

I've attached both files referenced. I'm using Arch Linux x86_64, I have all the dependencies installed.

[CMakeError.log.txt](https://github.com/monero-project/bitmonero/files/432636/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/monero-project/bitmonero/files/432637/CMakeOutput.log.txt)

**Comment by flounders** [comment]
Same message again using yaourt to build it. I typically use aura and it has had issues too. I've attached the output below.

```
-- outfile location is /tmp/yaourt-tmp-swilliams/aur-bitmonero-git/src/bitmonero/build/lib/libwallet_merged.a
CMake Error at tests/CMakeLists.txt:90 (set_property):
  set_property could not find TARGET gtest.  Perhaps it has not yet been
  created.


-- Configuring incomplete, errors occurred!
See also "/tmp/yaourt-tmp-swilliams/aur-bitmonero-git/src/bitmonero/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/yaourt-tmp-swilliams/aur-bitmonero-git/src/bitmonero/build/CMakeFiles/CMakeError.log".
```

[CMakeError.log.txt](https://github.com/monero-project/bitmonero/files/432988/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/monero-project/bitmonero/files/432989/CMakeOutput.log.txt)

**Comment by radfish** [comment]
Could you please attach the full cmake output that you get on the console, not in the CMakeOutput file?
Remember to delete the build directory and re-run the command (or just start from scratch), so that cmake is not using any cached data.

**Comment by radfish** [comment]
Also, do you have `gtest` package installed? If so, could you try uninstalling that package and retrying the build?

**Comment by flounders** [comment]
It built after I removed gtest. Otherwise, it didn't seem to matter what I'd do.

**Comment by radfish** [comment]
Could you please change the title to: cmake fails when gtest is installed on the system

**Comment by radfish** [comment]
gtest patch merged, this can be closed
